version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: setuptools
    versions:
    - 52.0.0
    - 53.0.0
    - 54.0.0
    - 54.1.1
    - 54.2.0
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: pytz
    versions:
    - "2020.5"
