language: python
matrix:
  include:
  - name: Python 3.7 on Xenial Linux
    python: 3.7
    dist: xenial
    install: python setup.py install
    script: python -m pip install coverage && python -m nose --with-xunit --with-coverage --cover-erase --cover-package=renfe --cover-xml && sonar-scanner -Dsonar.projectKey=gerardcl_renfe-cli -Dsonar.python.xunit.reportPath=nosetests.xml -Dsonar.python.coverage.reportPaths=coverage.xml
    addons:
      apt:
        packages:
        - pandoc
      sonarcloud:
        organization: gerardcl-github
        token:
          secure: "kfvzYdOUF89a6tSziG2NkVPXDD31x8uRnz6kfCoiVan+pZrc1ZXGzJc3XFiH3bgfQGNNJq39fkPkegTkFDrPzEox1S9lbfBl+e2elke3cxSN8DhExxrl9MecBNckyEacHSS2PEfDIDoxwXqzFGkRFwna4bBFHMvxkyU5jhRQVRgll7ZsT+MRHc3Q5Wl+/s75FK+mTVj5YsWwaqSAHLoXyP+bkNEnzqn1OKNMIkcMKMCD7B2ZNXeGd1QrD9duGX7Q4GlhVWrA+OXfokPJm1twg+kL4LSPJT62ychC0ewEDQ8tQ5dM+85VQSZJJJCr/5HDm5qHVX1cVqXMFKGEVuCdK5RKfX9Qq9ykKK0a0CtGw/SKieh6jL45GRTtyiDqhilwGy8SemLaVFy0kKqWVLifg7XCA8+aAoFjBR8R0M7a0btsP7dDZaohOUApiz9ifSCky4a8/Bys42a+chMV9AwdmgEcsLa8dlYo+uFM3Qckn8OTbr/60gDUMyFJ+DhStRWtnUQcu5JItLocbaFdNn4S6tSEPa4Ecrl+jemlfrFKGmv7oOTTruwINTT4LwbdZ9cdJ9/p+f0VZ0iRdxVQ//0pZpjhiDaqviorZQRXnuMZOXOR0osHdzl2L5HuBBw05OAJRvwTWzguTs+hVihskaeop+y1j3jmCp20jb9j9n7uum4="
    before_deploy: python -m pip install pypandoc pandoc twine --upgrade
    deploy:
      provider: pypi
      user: gerardcl
      password:
        secure: ZyJI8z6787HKrqoP1J1rYxEQsPG4rf0nDR1q4UsEaLJ5e2ERzv85VNhZUDUi9yXUZ5leiYHrQ3xJ0trr0UmeiPNdW4p3RzECt3ubGEgKTnpFXwle/V74YBjJ67k+UrxZits93RiLcYm03YxAU3nehTiqrjYFska4vfpix66yHTgrHS2/bo7To5Js/TMJn6ZGBUBGye/HgZG27TRg6plvvqqmVeGMGlH+m5/OvVDxXonIVFu1YVpcgBGkmhyREWa9XjSbfiqp9TX2SG8fy49oaZdoA3Xqo93QHhgAQHTfrkgkIzVts72jzlCUuqAPbzqKQOvATlZ1muupVkkrKb6R+qFQw3+ZnieFl532HkGuEIU+cVbds3v0VJ0s3UVKImi9oH2GY7qvayyMKDUWwFxNt/JSdrQLBjKPz5NJbBZPpQGDyDcDWpf38TAJ9ba02atV93uMMiy67ZaHxuChET3DleycM7NYMLtK+LK5qmIs1kdh8k6+huXXbUyuu2L6cHoKx936VYWxTPVNUDWGxF/4/68Zi60DXYHz5K3JG3pA3UiqmmdH7ZG2FMscesgAboMnXP0NP2DJUt8KNGaZM0s323TioytfIbiTd9N9Gx5iTsotziFG2YLRGtoFuvBRAUYgp3pyskIVQJu8aIM9iU61lKdWlZ7T1R89qxCFVzVx0OI=
      on:
        tags: true
      distributions: "sdist bdist_wheel"
      skip_existing: true
      skip_cleanup: true
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode10.2
    before_install: pip3 install --user requests nose --upgrade
    language: shell
    install: python3 setup.py install
    script: python3 -m nose
  - name: Python 3.7 on Windows
    os: windows
    language: shell
    before_install: wget --no-check-certificate https://www.renfe.com && choco install python --version=3.7.3 && pip install nose certifi --upgrade
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    install: python setup.py install
    script: python -m nose
notifications:
  email:
    on_success: never
    on_failure: always
