# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Check timetable for a given route"

on:
  workflow_dispatch:
  schedule:
    - cron: '25 */12 * * *'

jobs:
  get_timetable:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - date: "2023-04-21"
            origin: VALEN
            destination: BARCE
            toemail: "anna.samarra@gmail.com"
            minTrips: 2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Run renfe-cli
      id: running
      run: |
        renfe-cli --date ${{ matrix.date }} -o ${{ matrix.origin}} -t ${{ matrix.destination }} --output timetable.json
        echo "NUM_TRIPS=$(cat timetable.json | jq length)" >> $GITHUB_OUTPUT
    - name: Send email if condition is met
      if: ${{ steps.running.outputs.num_trips >= matrix.minTrips }}
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_TEMPLATE_ID: ${{ secrets.SENDGRID_TEMPLATE_ID }}
        SENDGRID_FROM_EMAIL: "geovannyalexanderr@gmail.com"
      run: |
        curl -X "POST" "https://api.sendgrid.com/v3/mail/send" \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "from": {
                    "email": "'"$SENDGRID_FROM_EMAIL"'"
                },
                "template_id": "'"$SENDGRID_TEMPLATE_ID"'",
                "personalizations":[
                  {
                    "to":[{ "email":"${{ matrix.toemail }}"}],
                    "dynamic_template_data": {
                        "origin": "${{ matrix.origin }}",
                        "destination": "${{ matrix.destination }}",
                        "date": "${{ matrix.date }}"
                    }
                  }
                ]
              }'
