# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Check timetable for a given route"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  get_timetable:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toemail: ["geovannyalexanderr@gmail.com", "anna.samarra@gmail.com"]
        include:
          - days: "2022-12-16"
            origin: VALEN
            destination: BARCE
          - days: "2022-12-21"
            origin: BARCE
            destination: 11208

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Run renfe-cli
      run: |
        renfe-cli --date ${{ matrix.days }} -o ${{ matrix.origin}} -t ${{ matrix.destination }} --output timetable.json
        echo "::set-output name=timetable::$(cat timetable.json)"
    - name: Send email if timetable is not empty
      if: fromJSON(steps.get_timetable.outputs.timetable).length > 0
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRIP_TEMPLATE_ID: ${{ secrets.SENDGRIP_TEMPLATE_ID }}
        SENDGRIP_FROM_EMAIL: "geovannyalexanderr@gmail.com"
      run: |
        curl -X "POST" "https://api.sendgrid.com/v3/mail/send" \
          -H 'Authorization: Bearer $SENDGRID_API_KEY' \
          -H 'Content-Type: application/json' \
          -d '{
                "from": {
                    "email": "$SENDGRIP_FROM_EMAIL"
                },
                "template_id": "$SENDGRIP_TEMPLATE_ID",
                "personalizations":[
                  {
                    "to":[{ "email":"${{ matrix.toemail }}"}],
                    "dynamic_template_data": {
                        "origin": "${{ matrix.origin }}",
                        "destination": "${{ matrix.destination }}",
                        "date": "${{ matrix.days }}"
                    }
                  }
                ]
              }'
